name: Python SDK CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install pipenv
      - run: pipenv install --dev
      - run: pipenv run pytest
      - name: Publish to PyPI
        if: success()
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pipenv run pip install --upgrade setuptools wheel
          pipenv run python setup.py sdist bdist_wheel
          pipenv run pip install twine
          pipenv run twine upload dist/*
