name: Python SDK Publish CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    environment: Development

    env:
      LOTUS_API_KEY: ${{ secrets.LOTUS_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel && pipenv update

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev
          
      - name: Test Pytest
        run: |
          pipenv run pytest

      - name: Publish to PyPI
        if: success()
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pipenv run pip install --upgrade setuptools wheel
          pipenv run python setup.py sdist bdist_wheel
          pipenv run pip install twine
          pipenv run twine upload dist/*
